config/routes.rb
Rails.application.routes.draw do
  resources :videos do
    collection do
      get :make_clip
    end
  end

  root 'home#welcome'

end

app/models/screenshot.rb
@video.content.gsub(/?../,"")
# require 'rubygems'
# require 'youtube-dl.rb'
# require 'streamio-ffmpeg'


# video = YoutubeDL::Video.new("https://www.youtube.com/watch?v=m1pchpDD5EU")
# video.options.configure do |c|
#   c.get_filename = true
#   c.output = "a.mp4"
#   c.simulate = true
#   c.extract_audio = true
#   c.audio_format = 'mp3'
# end
# video.download
# video.filename
# p "#{video.options.store[:output]}"
# options = {
#   username: 'someone',
#   password: 'password1',
#   rate_limit: '50K',
#   output: "a.mp4",
#   format: :worst
# }
# YoutubeDL.download "https://www.youtube.com/watch?v=H7HmzwI67ec", options
# p "a"
# video = "some-file.mp4"
# YoutubeDL.download "https://www.youtube.com/watch?v=H7HmzwI67ec", output: video
# system("ffmpeg -i #{video} -ss 00:00:30 -t 00:00:49 -async 1 final.mp4")

# movie = FFMPEG::Movie.new("output.mp4")
# ffmpeg -i movie -ss 00:00:03 -t 00:00:08 -async 1 cut.mp4
# movie.screenshot("tayler.jpg", seek_time: 20)
# ffmpeg -i output.mp4 -ss 00:00:03 -t 00:00:08 -async 1 cut.mp4

app/models/video.rb
class Video < ActiveRecord::Base
  has_attached_file :content,
                        # :url => "/uploads/videos/:id/:style/:basename.:extension",
                        # :path => ":rails_root/uploads/videos/:id_partition/:style/:basename.:extension",
                        :styles => {
                          # :mp4 => { :format => 'mp4' },
                          # :medium => { :geometry => "640x480", :format => 'flv' },
                          :thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10 }
                        },
                        :processors => [:transcoder]
  do_not_validate_attachment_file_type :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require 'streamio-ffmpeg'

class HomeController < ApplicationController
  def welcome
    @video = "https://www.youtube.com/watch?v=FIa8T9jbG9Q".gsub('watch?v=', 'embed/')
    p @video
    # movie = FFMPEG::Movie.new("#{Rails.root}/tmp/ireallylikeyou.mp4")
    # movie.screenshot("tayler.jpg", seek_time: 5)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy, :make_clip]

  def make_clip
    p params
    content = @video.content.url.gsub("?1451542062"," ").strip
    p content
    # content = @video.content
    str_time = params[:value1]
    end_time = params[:value2]
    p "ffmpeg -i #{content} -ss #{str_time} -t #{end_time} -async 1 final.mp4"
    #gsub or delete string letters after "?", and investigate why it puts ? at the end when saved
    system("ffmpeg -i '#{Rails.root}/public#{content}' -ss '#{str_time}' -t '#{end_time}' -async 1 final.mp4")
  end

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>

<!-- <iframe id="video" width="640" height="385" src="<%= @video %>" frameborder="1" allowfullscreen></iframe> -->
<video id="video" controls width="320" height="240" src="<%= Rails.root %>/app/assets/images/cut.mp4">
  <!-- <source src="/cut.mp4" type='video/mp4'> -->
</video>
<br>
<input type="button" value="play" onclick="video_play()">
<input type="button" value="pause" onclick="video_pause()">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoClip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.file_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


https://www.youtube.com/watch?v=nN6VR92V70M
ffmpeg -i "https://www.youtube.com/watch?v=nN6VR92V70M" -vcodec copy -acodec copy -map 0:6 -map 0:7 "outputfile.ts"

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<%= video_tag @video.content, :size => "320x240", :controls => true, preload:"auto", id:"target_video"%>

<input type="button" value="click to record" id="vd-Btn" />
<!-- <input type="button" value="pause" id="pauseBtn" />
<input type="button" value="stop" id="stopBtn" /> -->

<!-- <video>
  <source src="<%= @video.content %>" type='video/mp4;' />
</video> -->
<!-- <video>
  <source src="<%= @video.content %>", :size => "320x240", :controls => true %></source>
</video> -->
<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>


<script>
  $(document).ready(function(){
    var video = document.getElementById("target_video");
    var srt_time = 0
    var end_time = 0
    $("#vd-Btn").click(function () {
      if(video.paused){
        srt_time = video.currentTime;
        video.play();
        document.querySelector('input').value = "finish to clip"
      }else{
        end_time = video.currentTime;
        video.pause();
        document.querySelector('input').value = "click to record"
        send_ajax(srt_time, end_time)
      }
    })
    function send_ajax(value1,value2){
      $.ajax({
            url: "/videos/make_clip",
            type: "GET",
            data: {id: "<%= @video.id %>", value1,value2},
            beforeSend: function(){
              //$("body").find("*").attr("disabled", "disabled");
            },
            success : function(text) {
              alert("success")
            },
            error: function (xhr, ajaxOptions, thrownError) {
              alert("error");
              // alert(xhr.status);
            }
          })
    }
    // $("#pauseBtn").click(function () {
    //     video.pause();
    // });
    // $("#stopBtn").click(function () {
    //     video.pause();
    //     video.currentTime = 0;
    //     video.load();
    // });
  })
</script>